### ISSUE TITLE
Product Unit Show in Invoice

### ISSUE THREAD

**Issue by staraqeel** [Tech-Track/Hissab#1]
Please Show Product Unit in Sales Invoice , Remove Store Option and Add Unit on It.
Check Image
![unit](https://user-images.githubusercontent.com/55684243/65413354-b89f5600-de0a-11e9-8b6c-2d6426d39c01.PNG)

**Comment by BILAWAL1234123** [comment]
Done in adding sale invoice. 
Edit section is remaining yet.

**Comment by staraqeel** [comment]
In Add Section Verified. Please adjust Unit as Discuss.

**Comment by BILAWAL1234123** [comment]
done sir g. can you please check

**Comment by staraqeel** [comment]
Done
