### ISSUE TITLE
Invoice Report Format

### ISSUE THREAD

**Issue by staraqeel** [Tech-Track/Hissab#12]
Please Fix Invoice Report Format. Currently Font is Too Large, and Make Adjustment.

**Comment by BILAWAL1234123** [comment]
i will start work on it

**Comment by BILAWAL1234123** [comment]
@ulfatayaz  i am working on it

**Comment by BILAWAL1234123** [comment]
Done.

**Comment by staraqeel** [comment]
Only Font has been Changed. Please Make Arrangement, Alignment 
Check Image
![A4 INVOICE](https://user-images.githubusercontent.com/55684243/65508111-ece94400-dee8-11e9-9b30-6b9793e3f208.PNG)
nment, Size of Fields.

**Comment by BILAWAL1234123** [comment]
changed. can you check again sir g

**Comment by staraqeel** [comment]
Seems Good,
