### ISSUE TITLE
Stock Report/Register

### ISSUE THREAD

**Issue by staraqeel** [Tech-Track/Hissab#4]
Stock Report Adjustment, Label Setting, and Add Cost In Report.
Check Image For Your Idea.
Same Report Needed Item Wise Report/Category Wise
![stock](https://user-images.githubusercontent.com/55684243/65414894-09647e00-de0e-11e9-98aa-490b7d720d52.PNG)

**Comment by BILAWAL1234123** [comment]
Done

**Comment by staraqeel** [comment]
Format is Not Good.
Opening Qty Column Width
Sales Column Width
Make All Quantities Align Center
Rate Right Align,
Please Check Above Image

**Comment by BILAWAL1234123** [comment]
can you check again sir ?

**Comment by staraqeel** [comment]
Rest is good, Please Align All Qty in Center

**Comment by BILAWAL1234123** [comment]
done sir g

**Comment by staraqeel** [comment]
Done
