### ISSUE TITLE
Total In Hand Qty

### ISSUE THREAD

**Issue by staraqeel** [Tech-Track/Hissab#8]
Total In Hand Qty Should Show in Sales Invoice and Other Vouchers as Well, Like Purchase, Return Other

**Comment by BILAWAL1234123** [comment]
sir g quantity in hand is done in sale invoice adding and editing..  
it is still remaining in sale return add and editing and same in purchase and purchase return

**Comment by staraqeel** [comment]
In Sales Invoice Done. Only in Edit it Now Showing
